### ISSUE TITLE
tx drop

### ISSUE THREAD

**Issue by NathanHo1024** [solana-rpc-community/rpc-v2-specs#23]
I broadcast the rawTransaction by the solana-rpc and it return the txHash.
but i can't found it on the explorer.
why my tx will be dropped?
i add the prioritifee combudget instruction and add the mev-fee instruction in my tx. 
but the tx still dropped.
i wonder what's the fields will affect the tx confirmed?

**Comment by Reecetaylor96** [comment]
> I broadcast the rawTransaction by the solana-rpc and it return the txHash. but i can't found it on the explorer. why my tx will be dropped? i add the prioritifee combudget instruction and add the mev-fee instruction in my tx. but the tx still dropped. i wonder what's the fields will affect the tx confirmed?



There are several reasons why your transaction might be dropped on the Solana network, even after broadcasting it with priority fees and MEV fees.I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Metaplex Network DApps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
